---
title: "Let's practice - 10"
author: "Joao Lourenco"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

# Global options
knitr::opts_chunk$set(echo = TRUE)


# load libraries
library(flowCore)
library(ggcyto)

```


# Introduction


In this exercise we will use a 36-color spectral flow cytometry dataset from a study performed in the context of COVID-19 research.



# Import the FCS files


```{r import_data}

#1)Import the FCS files (course_datasets/FR_FCM_Z3WR/). Do not transform or truncate the values. 

# path to the directory with the fcs files
fcs.dir<- file.path( "course_datasets/FR_FCM_Z3WR/")

# read fcs files into a floSwet
fcs_data <- read.flowSet(path=fcs.dir, pattern="*.fcs", transformation = FALSE, truncate_max_range = FALSE) 


```


# Channels and antigens


```{r channels_and_antigens, fig.align='center'}


#2) Create a data frame with the list of channels and corresponding antigens, and plot it.
#Hint: get the antigens from the parameters of one of the flowFrame in the set
channels <- colnames(fcs_data)
antigen <- pData(parameters(fcs_data[[1]]))$desc
panel <- data.frame(channels = channels, antigen= antigen)

# plot
panel


```


# Convert from channel to antigen names


```{r convert_colnames}

#3) Convert the channel names in the expression matrices to the corresponding antigen names (where applicable)
colnames(fcs_data)[!is.na(antigen)] <- antigen[!is.na(antigen)] 


# check
head(exprs(fcs_data[[1]])[,c(5:10)])


```

# Time points


```{r time_points}


#4) Add a new column to the phenotypic data with the time point of the sample


# check sample names
# sampleNames(fcs_data)
#  [1] "0BF51C_0.fcs"  "0BF51C_14.fcs" "0BF51C_7.fcs"  "0E1F8E_0.fcs"  "0E1F8E_14.fcs" "0E1F8E_7.fcs"  "180E1A_0.fcs" 
#  [8] "180E1A_14.fcs" "180E1A_7.fcs"  "1A9B20_0.fcs"  "1A9B20_14.fcs" "1A9B20_7.fcs"  "61BBAD_0.fcs"  "61BBAD_14.fcs"
# [15] "61BBAD_7.fcs" 

# add column with time point
pData(fcs_data)$time_point <- rep(c("D0","D14","D7"),5)

# plot the phenotypic data
pData(fcs_data)


```


# Bivariate density plot



```{r bivariate_density_plot, fig.align='center', fig.height=10, fig.width=15}

#5) Create a bivariate density plot showing "FSC-H" against "HLA-DR" for all samples from day 0. Apply a flowJO inverse hyperbolic sine scale to the y axis ("HLA-DR")

# split by time point 
fcs_data.split <- split(fcs_data, pData(fcs_data)$time_point)

# create the bivariate density plot
autoplot(fcs_data.split$D0, x="FSC-H",y="HLA-DR", bins = 64) + scale_x_flowjo_biexp() + scale_y_flowjo_fasinh()

```
